"use strict";

const METER_DEFINITIONS = {
    "eastron_sdm120m": {
        "name": "Eastron SDM120M (1 phase)",
        "measurements": [
            {
                "name": "voltage",
                "address": 0,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "current",
                "address": 6,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 2
            },
            {
                "name": "active_power",
                "address": 12,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2
            },
            {
                "name": "apparent_power",
                "address": 18,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "apparent_power",
                "unit_of_measurement": "VA",
                "precision": 2
            },
            // {
            //     "name": "reactive_power",
            //     "address": 24,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "reactive_power",
            //     "unit_of_measurement": "var",
            //     "precision": 2
            // },
            // {
            //     "name": "power_factor",
            //     "address": 30,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "power_factor",
            //     "unit_of_measurement": " ",
            //     "precision": 2
            // },
            {
                "name": "frequency",
                "address": 70,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "frequency",
                "unit_of_measurement": "Hz",
                "precision": 2
            },
            {
                "name": "active_energy_import",
                "address": 72,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_export",
                "address": 74,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "total_active_energy",
                "address": 342,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
        ]
    },
    "eastron_sdm72dm": {
        "name": "Eastron SDM72D-M (3 phase)",
        "measurements": [
            {
                "name": "voltage_l1_n",
                "address": 0,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l2_n",
                "address": 2,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l3_n",
                "address": 4,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l1_l2",
                "address": 200,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l2_l3",
                "address": 202,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l3_l1",
                "address": 204,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "current_l1",
                "address": 6,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 2
            },
            {
                "name": "current_l2",
                "address": 8,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 2
            },
            {
                "name": "current_l3",
                "address": 10,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 2
            },
            {
                "name": "current_n",
                "address": 224,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 2
            },
            {
                "name": "active_power_l1",
                "address": 12,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2
            },
            {
                "name": "active_power_l2",
                "address": 14,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2
            },
            {
                "name": "active_power_l3",
                "address": 16,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2
            },
            // {
            //     "name": "apparent_power_l1",
            //     "address": 18,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "apparent_power",
            //     "unit_of_measurement": "VA",
            //     "precision": 2
            // },
            // {
            //     "name": "apparent_power_l2",
            //     "address": 20,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "apparent_power",
            //     "unit_of_measurement": "VA",
            //     "precision": 2
            // },
            // {
            //     "name": "apparent_power_l3",
            //     "address": 22,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "apparent_power",
            //     "unit_of_measurement": "VA",
            //     "precision": 2
            // },
            // {
            //     "name": "reactive_power_l1",
            //     "address": 24,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "reactive_power",
            //     "unit_of_measurement": "var",
            //     "precision": 2
            // },
            // {
            //     "name": "reactive_power_l2",
            //     "address": 26,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "reactive_power",
            //     "unit_of_measurement": "var",
            //     "precision": 2
            // },
            // {
            //     "name": "reactive_power_l3",
            //     "address": 28,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "reactive_power",
            //     "unit_of_measurement": "var",
            //     "precision": 2
            // },
            // {
            //     "name": "power_factor_l1",
            //     "address": 30,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "power_factor",
            //     "unit_of_measurement": " ",
            //     "precision": 2
            // },
            // {
            //     "name": "power_factor_l2",
            //     "address": 32,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "power_factor",
            //     "unit_of_measurement": " ",
            //     "precision": 2
            // },
            // {
            //     "name": "power_factor_l3",
            //     "address": 34,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "power_factor",
            //     "unit_of_measurement": " ",
            //     "precision": 2
            // },
            // {
            //     "name": "power_factor_total",
            //     "address": 62,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "power_factor",
            //     "unit_of_measurement": " ",
            //     "precision": 2
            // },
            {
                "name": "frequency",
                "address": 70,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "frequency",
                "unit_of_measurement": "Hz",
                "precision": 2
            },
            {
                "name": "active_energy_import",
                "address": 72,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_export",
                "address": 74,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_total",
                "address": 342,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_net",
                "address": 396,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
        ],
    },
    "eastron_sdm630m": {
        "name": "Eastron SDM630M (3 phase)",
        "measurements": [
            {
                "name": "voltage_l1_n",
                "address": 0,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l2_n",
                "address": 2,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l3_n",
                "address": 4,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l1_l2",
                "address": 200,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l2_l3",
                "address": 202,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "voltage_l3_l1",
                "address": 204,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 2
            },
            {
                "name": "current_l1",
                "address": 6,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 2
            },
            {
                "name": "current_l2",
                "address": 8,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 2
            },
            {
                "name": "current_l3",
                "address": 10,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 2
            },
            {
                "name": "current_n",
                "address": 224,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 2
            },
            {
                "name": "active_power_l1",
                "address": 12,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2
            },
            {
                "name": "active_power_l2",
                "address": 14,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2
            },
            {
                "name": "active_power_l3",
                "address": 16,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2
            },
            // {
            //     "name": "apparent_power_l1",
            //     "address": 18,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "apparent_power",
            //     "unit_of_measurement": "VA",
            //     "precision": 2
            // },
            // {
            //     "name": "apparent_power_l2",
            //     "address": 20,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "apparent_power",
            //     "unit_of_measurement": "VA",
            //     "precision": 2
            // },
            // {
            //     "name": "apparent_power_l3",
            //     "address": 22,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "apparent_power",
            //     "unit_of_measurement": "VA",
            //     "precision": 2
            // },
            // {
            //     "name": "reactive_power_l1",
            //     "address": 24,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "reactive_power",
            //     "unit_of_measurement": "var",
            //     "precision": 2
            // },
            // {
            //     "name": "reactive_power_l2",
            //     "address": 26,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "reactive_power",
            //     "unit_of_measurement": "var",
            //     "precision": 2
            // },
            // {
            //     "name": "reactive_power_l3",
            //     "address": 28,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "reactive_power",
            //     "unit_of_measurement": "var",
            //     "precision": 2
            // },
            // {
            //     "name": "power_factor_l1",
            //     "address": 30,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "power_factor",
            //     "unit_of_measurement": " ",
            //     "precision": 2
            // },
            // {
            //     "name": "power_factor_l2",
            //     "address": 32,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "power_factor",
            //     "unit_of_measurement": " ",
            //     "precision": 2
            // },
            // {
            //     "name": "power_factor_l3",
            //     "address": 34,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "power_factor",
            //     "unit_of_measurement": " ",
            //     "precision": 2
            // },
            // {
            //     "name": "power_factor_total",
            //     "address": 62,
            //     "input_type": "input",
            //     "data_type": "float32",
            //     "state_class": "measurement",
            //     "device_class": "power_factor",
            //     "unit_of_measurement": " ",
            //     "precision": 2
            // },
            {
                "name": "frequency",
                "address": 70,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "measurement",
                "device_class": "frequency",
                "unit_of_measurement": "Hz",
                "precision": 2
            },
            {
                "name": "active_energy_import",
                "address": 72,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_export",
                "address": 74,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_import_resettable",
                "address": 388,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_export_resettable",
                "address": 390,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_total",
                "address": 342,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_import_l1",
                "address": 346,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_import_l2",
                "address": 348,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_import_l3",
                "address": 350,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_export_l1",
                "address": 352,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_export_l2",
                "address": 354,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
            {
                "name": "active_energy_export_l3",
                "address": 356,
                "input_type": "input",
                "data_type": "float32",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 3
            },
        ],
    },
    "abb_d11": {
        "name": "ABB D11 (1 phase)",
        "measurements": [
            {
                "name": "active_energy_import",
                "address": 20480,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export",
                "address": 20484,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_net",
                "address": 20488,
                "input_type": "holding",
                "data_type": "int64",
                "state_class": "total",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_tariff1",
                "address": 20848,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_tariff1",
                "address": 20852,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_tariff2",
                "address": 20856,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_tariff2",
                "address": 20860,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_tariff3",
                "address": 20864,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_tariff3",
                "address": 20868,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_tariff4",
                "address": 20872,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_tariff4",
                "address": 20876,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_l1",
                "address": 21600,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_l1",
                "address": 21612,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_net_l1",
                "address": 21624,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_resettable",
                "address": 21804,
                "input_type": "holding",
                "data_type": "int64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_resettable",
                "address": 21808,
                "input_type": "holding",
                "data_type": "int64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "voltage_l1_n",
                "address": 23296,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 1,
                "scale": 0.1,
            },
            {
                "name": "current_l1",
                "address": 23308,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 1,
                "scale": 0.1
            },
            {
                "name": "current_n",
                "address": 23314,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 1,
                "scale": 0.1
            },
            {
                "name": "active_power_total",
                "address": 23316,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2,
                "scale": 0.01
            },
            {
                "name": "active_power_l1",
                "address": 23318,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2,
                "scale": 0.01
            },
        ],
        // Buttons (if that ever becomes a thing in HA):
        // 8F0B -> write 1 to "Reset input counter (Input 1)"
        // 8F1B -> write 1 to "Reset resettable active energy import"
        // 8F1C -> write 1 to "Reset resettable active energy export"
        // 8F1D -> write 1 to "Reset resettable reactive energy import"
        // 8F1E -> write 1 to "Reset resettable reactive energy export"
        // 8F31 -> write 1 to "Reset system log"
        // 8F32 -> write 1 to "Reset event log"
        // 8A07 -> Set tariff (1,2,3,4) - 8C90 must be 1
    },
    "abb_d13": {
        "name": "ABB D13 (3 phase)",
        "measurements": [
            {
                "name": "active_energy_import",
                "address": 20480,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export",
                "address": 20484,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_net",
                "address": 20488,
                "input_type": "holding",
                "data_type": "int64",
                "state_class": "total",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_tariff1",
                "address": 20848,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_tariff1",
                "address": 20852,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_tariff2",
                "address": 20856,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_tariff2",
                "address": 20860,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_tariff3",
                "address": 20864,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_tariff3",
                "address": 20868,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_tariff4",
                "address": 20872,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_tariff4",
                "address": 20876,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_l1",
                "address": 21600,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_l2",
                "address": 21604,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_l3",
                "address": 21608,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_l1",
                "address": 21612,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_l2",
                "address": 21616,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_l3",
                "address": 21620,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_net_l1",
                "address": 21624,
                "input_type": "holding",
                "data_type": "uint64",
                "state_class": "total",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_net_l2",
                "address": 21628,
                "input_type": "holding",
                "data_type": "int64",
                "state_class": "total",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_net_l3",
                "address": 21632,
                "input_type": "holding",
                "data_type": "int64",
                "state_class": "total",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_import_resettable",
                "address": 21804,
                "input_type": "holding",
                "data_type": "int64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "active_energy_export_resettable",
                "address": 21808,
                "input_type": "holding",
                "data_type": "int64",
                "state_class": "total_increasing",
                "device_class": "energy",
                "unit_of_measurement": "kWh",
                "precision": 2,
                "scale": 0.01,
            },
            {
                "name": "voltage_l1_n",
                "address": 23296,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 1,
                "scale": 0.1,
            },
            {
                "name": "voltage_l2_n",
                "address": 23298,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 1,
                "scale": 0.1,
            },
            {
                "name": "voltage_l3_n",
                "address": 23300,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 1,
                "scale": 0.1,
            },
            {
                "name": "voltage_l1_l2",
                "address": 23302,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 1,
                "scale": 0.1,
            },
            {
                "name": "voltage_l2_l3",
                "address": 23304,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 1,
                "scale": 0.1,
            },
            {
                "name": "voltage_l1_l3",
                "address": 23306,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "voltage",
                "unit_of_measurement": "V",
                "precision": 1,
                "scale": 0.1,
            },
            {
                "name": "current_l1",
                "address": 23308,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 1,
                "scale": 0.1
            },
            {
                "name": "current_l2",
                "address": 23310,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 1,
                "scale": 0.1
            },
            {
                "name": "current_l3",
                "address": 23312,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 1,
                "scale": 0.1
            },
            {
                "name": "current_n",
                "address": 23314,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "current",
                "unit_of_measurement": "A",
                "precision": 1,
                "scale": 0.1
            },
            {
                "name": "active_power_total",
                "address": 23316,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2,
                "scale": 0.01
            },
            {
                "name": "active_power_l1",
                "address": 23318,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2,
                "scale": 0.01
            },
            {
                "name": "active_power_l2",
                "address": 23320,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2,
                "scale": 0.01
            },
            {
                "name": "active_power_l3",
                "address": 23322,
                "input_type": "holding",
                "data_type": "uint32",
                "state_class": "measurement",
                "device_class": "power",
                "unit_of_measurement": "W",
                "precision": 2,
                "scale": 0.01
            },
            // Same "buttons" as D13
        ],
    },
}

function get_meter_types() {
    let ret = [];

    for (const [key, value] of Object.entries(METER_DEFINITIONS)) {
        ret.push(
            {
                "key": key,
                "name": value["name"]
            }
        );
    }

    return ret;
}

function generate_meter_yaml(meter_type, name, modbus_id, scan_interval) {
    if (!Object.hasOwn(METER_DEFINITIONS, meter_type)) {
        return `Unknown meter type: ${meter_type}`;
    }

    let ret = "";

    for (const measurement of METER_DEFINITIONS[meter_type]["measurements"]) {
        ret += `
- name: "${name}_${measurement.name}"
  unique_id: "${name}_${measurement.name}"
  slave: ${modbus_id}
  address: ${measurement.address}
  input_type: "${measurement.input_type}"
  data_type: "${measurement.data_type}"
  state_class: "${measurement.state_class}"
  device_class: "${measurement.device_class}"
  unit_of_measurement: "${measurement.unit_of_measurement}"
  precision: ${measurement.precision}
  scan_interval: ${scan_interval}`;

        if (Object.hasOwn(measurement, "scale")) {
            ret += `\n  scale: ${measurement.scale}`
        }
    }

    return ret;
}